---
- name: "install pyenv"
  homebrew: name=pyenv state=present

- name: "install pyenv virtualenv"
  homebrew: name=pyenv-virtualenv state=present

- name: "install rbenv"
  homebrew: name=rbenv state=present

- name: "install ruby build"
  homebrew: name=ruby-build state=present

- name: "install nodenv"
  homebrew: name=nodenv state=present

- name: "install node"
  homebrew: name=node state=present

- name: "install go"
  homebrew: name=go state=present

- name: "install htop"
  homebrew: name=htop state=present

- name: "install java"
  homebrew_cask: name=java state=present

- name: "install reattach to user namespace"
  homebrew: name=reattach-to-user-namespace state=present

- name: "install fasd"
  homebrew: name=fasd state=present

- name: "install terminal notifier"
  homebrew: name=terminal-notifier state=present

- name: "install vagrant"
  homebrew_cask: name=vagrant state=present

- name: "install docker"
  homebrew: name=docker state=present

- name: "install dvm"
  homebrew: name=dvm state=present
